-- ============================================================
-- MIGRACIÓN RUTAS FORMATIVAS — Brota
-- Ejecutar en el SQL Editor de Supabase (o vía psql)
-- ============================================================
-- Contenido estático por área académica (mismas 14 claves que ya usan
-- Profesiones.jsx / TestResult.jsx / vocacionalCategorias.js). Nada de
-- scraping de pensums ni llamadas en vivo a una API de LLM: el contenido
-- se escribió/curó una sola vez (agosto 2026 — temas_previos/proyectos/
-- recursos escritos a mano; materias_comunes curado con ayuda de otra IA
-- + revisión manual, ver commits de agosto 2026) y se sirve tal cual,
-- para no generar costo ni dependencia externa en /dashboard/rutas.

CREATE TABLE IF NOT EXISTS contenido_rutas (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  area              TEXT UNIQUE NOT NULL,
  materias_comunes  JSONB NOT NULL DEFAULT '[]',
  temas_previos     JSONB NOT NULL DEFAULT '[]',
  proyectos         JSONB NOT NULL DEFAULT '[]',
  recursos          JSONB NOT NULL DEFAULT '[]', -- [{ "titulo": "...", "url": "..." }]
  created_at        TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE contenido_rutas ADD COLUMN IF NOT EXISTS materias_comunes JSONB NOT NULL DEFAULT '[]';

-- RLS: solo el backend (SUPABASE_SERVICE_KEY) accede.
ALTER TABLE contenido_rutas ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "solo_service_role" ON contenido_rutas;
CREATE POLICY "solo_service_role" ON contenido_rutas FOR ALL TO service_role USING (true) WITH CHECK (true);

INSERT INTO contenido_rutas (area, materias_comunes, temas_previos, proyectos, recursos) VALUES
('administrativo', '["Administración","Contabilidad","Economía","Finanzas","Mercadeo","Gestión Humana","Estadística","Emprendimiento","Planeación Estratégica","Comercio Internacional","Gestión de Operaciones","Gestión de Proyectos"]'::jsonb, '["Matemáticas básicas","Comunicación","Excel","Economía básica","Pensamiento analítico"]'::jsonb, '["Plan de negocio","Presupuesto empresarial","Estudio de mercado","Plan de marketing","Dashboard financiero","Modelo de emprendimiento"]'::jsonb, '[{"url":"https://www.sena.edu.co/","titulo":"SENA"},{"url":"https://www.ccb.org.co/","titulo":"Cámara de Comercio de Bogotá"},{"url":"https://www.banrep.gov.co/","titulo":"Banco de la República"}]'::jsonb),
('ambiental', '["Ecología","Química Ambiental","Biología","Hidrología","Gestión Ambiental","Legislación Ambiental","Cambio Climático","Evaluación de Impacto Ambiental","Manejo de Residuos","Cartografía y SIG","Educación Ambiental","Desarrollo Sostenible"]'::jsonb, '["Biología básica","Química básica","Ecología","Método científico","Actualidad ambiental"]'::jsonb, '["Diagnóstico ambiental de un espacio cercano","Proyecto de reciclaje escolar","Huerta urbana","Campaña de sensibilización ambiental","Monitoreo de un ecosistema local"]'::jsonb, '[{"url":"https://www.minambiente.gov.co/","titulo":"Ministerio de Ambiente y Desarrollo Sostenible"},{"url":"https://www.parquesnacionales.gov.co/","titulo":"Parques Nacionales Naturales de Colombia"},{"url":"https://www.ideam.gov.co/","titulo":"IDEAM"}]'::jsonb),
('arte', '["Dibujo","Historia del Arte","Teoría del Color","Composición","Tipografía","Diseño Gráfico","Ilustración","Fotografía","Diseño UX/UI","Modelado","Animación","Portafolio"]'::jsonb, '["Dibujo básico","Creatividad","Composición visual","Manejo básico de software de diseño"]'::jsonb, '["Identidad visual","Cartel","Ilustración editorial","Prototipo UX/UI","Animación corta","Portafolio profesional"]'::jsonb, '[{"url":"https://helpx.adobe.com/learn.html","titulo":"Adobe Learn"},{"url":"https://help.figma.com/hc/en-us/categories/360002051613-Learn-design","titulo":"Figma Learn"}]'::jsonb),
('ciencias', '["Biología","Química","Física","Matemáticas","Geología","Ecología","Microbiología","Genética","Estadística","Métodos de Investigación","Bioquímica","Ciencias Ambientales"]'::jsonb, '["Álgebra","Biología básica","Química básica","Física básica","Método científico"]'::jsonb, '["Experimento científico","Colección de datos ambientales","Modelo ecológico","Informe de laboratorio","Investigación experimental"]'::jsonb, '[{"url":"https://minciencias.gov.co/","titulo":"Ministerio de Ciencia"},{"url":"https://www.ideam.gov.co/","titulo":"IDEAM"},{"url":"https://bibliotecadigital.minciencias.gov.co/","titulo":"Biblioteca Virtual de Ciencia"}]'::jsonb),
('comunicacion', '["Teoría de la Comunicación","Redacción","Periodismo","Comunicación Digital","Producción Audiovisual","Fotografía","Diseño Editorial","Narrativa","Comunicación Organizacional","Publicidad","Investigación de Medios","Ética de la Comunicación"]'::jsonb, '["Lectura","Escritura","Creatividad","Herramientas digitales","Cultura general"]'::jsonb, '["Podcast","Blog periodístico","Campaña digital","Documental corto","Revista digital","Plan de comunicación"]'::jsonb, '[{"url":"https://www.rtvc.gov.co/","titulo":"RTVC"},{"url":"https://www.mintic.gov.co/","titulo":"MinTIC"},{"url":"https://grow.google/intl/es/courses-and-tools/","titulo":"Google Digital Garage"}]'::jsonb),
('deporte', '["Anatomía","Fisiología del Ejercicio","Biomecánica","Entrenamiento Deportivo","Pedagogía del Deporte","Nutrición Deportiva","Psicología del Deporte","Recreación y Tiempo Libre","Primeros Auxilios","Lesiones Deportivas","Evaluación Física","Gestión Deportiva"]'::jsonb, '["Biología básica","Anatomía básica","Hábitos de actividad física","Nutrición básica","Trabajo en equipo"]'::jsonb, '["Rutina de entrenamiento propia","Plan de actividad física para un grupo","Campaña de hábitos saludables","Organización de un torneo escolar","Diario de rendimiento deportivo"]'::jsonb, '[{"url":"https://www.mindeporte.gov.co/","titulo":"Ministerio del Deporte"},{"url":"https://www.sena.edu.co/","titulo":"SENA"}]'::jsonb),
('diseño', '["Dibujo","Historia del Arte","Teoría del Color","Composición","Tipografía","Diseño Gráfico","Ilustración","Fotografía","Diseño UX/UI","Modelado","Animación","Portafolio"]'::jsonb, '["Dibujo básico","Creatividad","Composición visual","Manejo básico de software de diseño"]'::jsonb, '["Identidad visual","Cartel","Ilustración editorial","Prototipo UX/UI","Animación corta","Portafolio profesional"]'::jsonb, '[{"url":"https://helpx.adobe.com/learn.html","titulo":"Adobe Learn"},{"url":"https://help.figma.com/hc/en-us/categories/360002051613-Learn-design","titulo":"Figma Learn"}]'::jsonb),
('educacion', '["Pedagogía","Didáctica","Psicología del Desarrollo","Evaluación Educativa","Currículo","Investigación Educativa","Inclusión Educativa","Tecnologías Educativas","Gestión Educativa","Filosofía de la Educación","Práctica Pedagógica","Comunicación Educativa"]'::jsonb, '["Lectura crítica","Comunicación","Psicología básica","Investigación","Manejo de herramientas digitales"]'::jsonb, '["Secuencia didáctica","Clase interactiva","Material educativo digital","Proyecto de inclusión","Instrumento de evaluación","Investigación educativa"]'::jsonb, '[{"url":"https://www.mineducacion.gov.co/","titulo":"Ministerio de Educación Nacional"},{"url":"https://www.colombiaaprende.edu.co/","titulo":"Colombia Aprende"}]'::jsonb),
('humanidades', '["Filosofía","Historia","Literatura","Ética","Lógica","Epistemología","Antropología Filosófica","Estética","Lenguaje y Comunicación","Historia del Pensamiento","Metodología de la Investigación","Cultura y Sociedad"]'::jsonb, '["Lectura crítica","Escritura académica","Historia general","Pensamiento crítico","Cultura general"]'::jsonb, '["Ensayo filosófico","Club de lectura","Línea de tiempo histórica","Debate argumentativo","Investigación sobre un movimiento cultural"]'::jsonb, '[{"url":"https://www.bibliotecanacional.gov.co/","titulo":"Biblioteca Nacional de Colombia"},{"url":"https://www.mincultura.gov.co/","titulo":"Ministerio de Cultura"}]'::jsonb),
('juridico', '["Introducción al Derecho","Derecho Constitucional","Derecho Civil","Derecho Penal","Derecho Laboral","Derecho Comercial","Derecho Administrativo","Derecho Procesal","Derecho Internacional","Derechos Humanos","Teoría del Estado","Argumentación Jurídica"]'::jsonb, '["Lectura crítica","Redacción","Argumentación","Historia","Constitución Política de Colombia"]'::jsonb, '["Análisis de una sentencia","Simulación de audiencia","Concepto jurídico","Análisis de contrato","Investigación sobre derechos fundamentales"]'::jsonb, '[{"url":"https://www.secretariasenado.gov.co/","titulo":"Secretaría del Senado"},{"url":"https://www.corteconstitucional.gov.co/","titulo":"Corte Constitucional"},{"url":"https://www.minjusticia.gov.co/","titulo":"Ministerio de Justicia"}]'::jsonb),
('negocios', '["Administración","Contabilidad","Economía","Finanzas","Mercadeo","Gestión Humana","Estadística","Emprendimiento","Planeación Estratégica","Comercio Internacional","Gestión de Operaciones","Gestión de Proyectos"]'::jsonb, '["Matemáticas básicas","Comunicación","Excel","Economía básica","Pensamiento analítico"]'::jsonb, '["Plan de negocio","Presupuesto empresarial","Estudio de mercado","Plan de marketing","Dashboard financiero","Modelo de emprendimiento"]'::jsonb, '[{"url":"https://www.sena.edu.co/","titulo":"SENA"},{"url":"https://www.ccb.org.co/","titulo":"Cámara de Comercio de Bogotá"},{"url":"https://www.banrep.gov.co/","titulo":"Banco de la República"}]'::jsonb),
('salud', '["Anatomía","Fisiología","Bioquímica","Microbiología","Farmacología","Patología","Epidemiología","Genética","Nutrición","Salud Pública","Bioética","Primeros Auxilios"]'::jsonb, '["Biología","Química","Anatomía básica","Método científico","Lectura crítica"]'::jsonb, '["Mapa del cuerpo humano","Campaña de prevención","Infografía de hábitos saludables","Base de datos epidemiológica","Proyecto de promoción de la salud"]'::jsonb, '[{"url":"https://www.minsalud.gov.co/","titulo":"Ministerio de Salud y Protección Social"},{"url":"https://www.who.int/","titulo":"Organización Mundial de la Salud"}]'::jsonb),
('social', '["Sociología","Antropología","Historia","Geografía","Ciencia Política","Metodología de Investigación","Estadística Social","Relaciones Internacionales","Derechos Humanos","Teoría Social","Políticas Públicas","Economía Social"]'::jsonb, '["Historia","Lectura crítica","Escritura","Geografía","Investigación básica"]'::jsonb, '["Investigación social","Encuesta comunitaria","Mapa social","Análisis de política pública","Historia local","Proyecto de intervención comunitaria"]'::jsonb, '[{"url":"https://www.dane.gov.co/","titulo":"DANE"},{"url":"https://www.banrep.gov.co/","titulo":"Banco de la República"},{"url":"https://www.mineducacion.gov.co/","titulo":"Ministerio de Educación Nacional"}]'::jsonb),
('tecnologia', '["Programación I","Programación II","Estructuras de Datos","Bases de Datos","Redes","Ingeniería de Software","Sistemas Operativos","Arquitectura de Software","Desarrollo Web","Seguridad Informática","Inteligencia Artificial","Computación en la Nube"]'::jsonb, '["Lógica de programación","Algoritmos","Matemáticas básicas","Python o JavaScript","Git y GitHub"]'::jsonb, '["Calculadora","To-do list","API REST","Aplicación web CRUD","Sistema de inventario","Chat en tiempo real","Proyecto con inteligencia artificial"]'::jsonb, '[{"url":"https://oferta.senasofiaplus.edu.co/sofia-oferta/","titulo":"SENA Sofia Plus"},{"url":"https://www.freecodecamp.org/","titulo":"freeCodeCamp"},{"url":"https://developer.mozilla.org/","titulo":"MDN Web Docs"},{"url":"https://skills.github.com/","titulo":"GitHub Skills"}]'::jsonb)
ON CONFLICT (area) DO UPDATE SET
  materias_comunes = EXCLUDED.materias_comunes,
  temas_previos     = EXCLUDED.temas_previos,
  proyectos         = EXCLUDED.proyectos,
  recursos          = EXCLUDED.recursos;
